name: landloard
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^0.13.6
  http_parser: ^4.0.2
  fluttertoast: ^8.2.4
  flutter_gif: ^0.0.4
  hexcolor: ^3.0.1
  carousel_slider: ^4.2.1
  google_maps_flutter: ^2.3.0
  flutter_rating_bar: ^4.0.1
  flutter_html: ^2.2.1
  provider: ^6.1.1
  device_preview: ^1.1.0
  super_banners: ^0.0.1
  shimmer: ^3.0.0
  cached_network_image: ^3.2.0
  url_launcher: ^6.1.11
  share_plus: ^6.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/companyLogo/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
